name: Ion_Sens_Dash
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.1
  - numpy=1.24
  - pandas=2.0
  - panel=1.1
  - bokeh=3.1
  - hvplot=0.8
  - holoviews=1.16
  - matplotlib=3.7
  - jupyter=1.0
  - nbconvert=7.4
  - scikit-learn=1.2
  - pip:
    - tensorflow==2.13.0
    - joblib==1.3.1
