name: ion_sensitivity
channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:
  - python=3.9.19
  - pip=23.3.1
  - numpy=1.26.3
  - pandas=2.2.1
  - panel=1.4.4
  - bokeh=3.4.1
  - hvplot=0.10.0
  - holoviews=1.19.0
  - matplotlib=3.8.0
  - jupyter
  - pip:
    - keras==2.10.0
    - tensorflow==2.10.0
    - joblib==1.2.0
    - scikit-learn==1.0.2
