name: Ion_Sens_Dash3
channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - panel
  - bokeh
  - hvplot
  - holoviews
  - matplotlib
  - jupyter
  - nbconvert
  - pip:
    - keras==2.11
    - tensorflow==2.11
    - joblib
    - scikit-learn
