name: Ion_Sens_Dash2
channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - panel
  - bokeh
  - hvplot
  - holoviews
  - matplotlib
  - jupyter
  - nbconvert
  - pip:
    - keras
    - tensorflow
    - joblib
    - scikit-learn
