name: Ion_Sens_Dash
channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:
  - python=3.9.18
  - pip
  - numpy
  - pandas
  - panel==1.4.4
  - bokeh==3.4.1
  - hvplot==0.10.0
  - holoviews==1.19.0
  - matplotlib
  - jupyter
  - nbconvert
  - pip:
    - keras==2.10.0
    - tensorflow==2.10.0
    - joblib==1.2.0
    - scikit-learn==1.0.2
