name: Ion_Sens_Dash
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - nbconvert=7.7.3
  - panel=1.2.1
  - bokeh=3.2.2
  - hvplot=0.8.4
  - holoviews=1.17.1
  - joblib
  - pip
  - pip:
    - tensorflow==2.13.0
